name: 52 Week High

on:
  workflow_dispatch:

jobs:
  fetch-52-week-high:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Fetch 52 Week High Data
      run: |
        mkdir -p market
        curl -X GET "https://www.nseindia.com/api/live-analysis-data-52weekhighstock" \
          -H "accept: */*" \
          -H "accept-language: en-US,en;q=0.9,hi;q=0.8,ta;q=0.7" \
          -H "cache-control: no-cache" \
          -H "cookie: _ga=GA1.1.482592878.1723464796; _ga_87M7PJ3R97=GS1.1.1723486278.2.1.1723486302.36.0.0; _abck=A2F2C7BE639605F40900B55F79849635~0~YAAQVV06F9VqzV+RAQAAB6fvfQzYgDofIvBCwcumNPzEqiGkzr9ENvDTW7+jY9vsMxM/Pvka4ySCKMeJrKyek9jpOkqNZSt64C5EFugkxN1RrjO/NUD49CHImqOfympxP2R8wR1fNgaykgJp/mHnRpIh2FbKarANmFx8tTS2H/jwfWsCtxlfs5CZVfLgJ4SnFBYKC9EnES8yc6hEPcSJrY3jteN+1b5i4gqvF+PYey25svZ9PqB80jv2mw1MEH8u447Lvi8YQODk5AgIVRdEbwWXDaYadGO1SE15TSqpQWUXxpxy5XRE35yRRRaizBw5gL4T9HkjxoYgfbIn9lOMa/t6p0KkWtRWj7Qsipguokwo0wCP62KT671xANDSSs5ywwsNwJpehFNQ+HpE9t9KVhJfOglPCUHhGAA=~-1~-1~-1; bm_sz=DE2490D999709571C883EB52928FF3F0~YAAQVV06F9hqzV+RAQAAB6fvfRhOwka0CPf4QfPJxMeO/5HhXvQz3DWtw+07Dz6/mBug4pfh4fKfafO3NosuY2BnLtEBkJIOcFWTn/kQCUDAwx+A+9e4wq6ReikwKOl5GywywIKESjAam5AOG40bQNHvboyVK2dedaY97URqEfYUiwSV2hPfX1M6A9xp820AumP9YpnJyOiCJOVBvKeEadgm9uh+B8BpgWYazki4CQLF2Rezw8Qwcu4g0N/hAThOiFacGqUyBKd/5O29k1xlbQEkB1wiW3n7dukcbo+tEiJlxRvlwa4GNhfDJjmuWBNzoYufsm8sNjEbs9JPZGLhEkrTiKK3ZOA+jXiPSsBISxGeMZDTvz+t4apamX1gMv4pUmXeRKPG6JU5aYU2hw==~3289650~3619125; defaultLang=en; nsit=n7kzmHinel3VCjU0RgbRIa8s; AKA_A2=A; ak_bmsc=C3761D3C892E43E836938278490B7BC7~000000000000000000000000000000~YAAQds8uF9suWWGRAQAAt/+QfhgYC2vrucnFOBPhR4z+lJUrhdPnmZtssd4uOdww9zmluL+w/GHKS0/7V3Ubx+4eEjxEyFDZ1uRlFx+lkPDsjtuUztB1t82oV8W3DrpWBrOeO1CssOfe5oLA5+OeB2esiMw4B+c46Ke5sIdzqdjV48gPMGQVKoht9AYR/NYUt8F8Ylp88fiysr4qNoKW+s2Hub/EuiENeqVyQptNgNpQM9f1hZclEwzisLIJrHtKK/y6GyXnLI3KJY5UwmxJX/ytEc2eQM+M6J+yruKFGAgmOo1ZgYaZseSmHmryv3JnanrDzDM8IBBC/qvOKQmm/rnzJHSm4Ld0O+JLkd5H5Xn9Ts0I3hKlmWrtKL5XJyJTjbRdI8sEvU3k89kG+XxRsuKqqm2ezTlX21GnqCCf; nseappid=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcGkubnNlIiwiYXVkIjoiYXBpLm5zZSIsImlhdCI6MTcyNDQwNTM1MiwiZXhwIjoxNzI0NDEyNTUyfQ.FCgAgyejqhsg7BHrJgfW6tBR5vqMgsTvShYxSvEyvTs; bm_mi=AE884A090BC198323685EC3DD495C449~YAAQhc8uF2fQZH6RAQAA64mRfhgUL7JpdJIYU4Xf7QL4RccrhVvxcGX2SYoIrWKLaykEVte7zaPHydSHDPG6KdQI5sOXgyPLBL2Ekear5j9WO2sJ5rpmHK5xUklokDuKg0V2vLbWCljTj94BjJZC4TVBzHndkjYchAEoWejv5urgK+orkBt5lv+ve9bvuXv4ILUAnrcmE2nkABU+kGaf+3g+caTpDlTD73y8R8DakadEceZfxYmu2QdWnwcVI1XUIhw3Se0/iPwldZOXzet1m1MaSAZmXqnjr5Ziw5F4Z6K4q7lix6BmXYXQvDT56LqZxMx6YC0oa3CDp4O0hgUixPXrWDzs72iSgok9DZ1tDfaALVdnrw==~1; bm_sv=7665E08DA42C3C41446FC49C5D6B578A~YAAQds8uFxtaWWGRAQAASZWRfhhnl0/VXN6jSN6k7YlmznmJX73gr9nRaxtJP+5thwHQyNi1WI/goFTQWY6WgBASpF/naSSVS8mS3X8iBpcze7uDm+dUrgL9lOxct8xGSrZfQycqee1NBO4ro0aXQ9VR2FyXCSI9SrOt7g+IJj7ljoC+kAUAtvS4y6LIkiOve7tmY5Yv29MVL77VKhlg69bWiAVqmhajxZJagUBnfMI7kYvRDTVZHacCcQgVwWbRUUe23A==~1; _abck=A2F2C7BE639605F40900B55F79849635~-1~YAAQpV06F0TNLl6RAQAA9luWfgzTgHXVUEh08H3d+yxq3tLLbzb9Mhk5oyNVtEufO8g9+7Lfo3BdILUpvTKIWWM8G9yq0aWywy9sJDAM6V/Ysya4uT43zzMzb0LUIEVrz9q3vUM7E7PTWDPt6uHEM7O8sMrPYBfgpXmz+GSThM71t23JrnTPAnarNbXSfUKLBkNBGKkbFDnoOs7ItOzrk4kfHhRvBjzTUotmruHQi9cAPGsfLLaX5FvDLVL0YCxzu0M6jeir4AgEIjoNU71cDoRxqlp9m+budr6OKBSXY2y1f+/sleDWE7nqU0MBdSaglsyiXqesT0yiVuu85Pjdpe4kSyV3lLrwnBtMvw4C8X6IeSyS6ImrLZw5EE4V3t//URXLK6Ezq91RvIQHjqt55EY3ZgQnOZOKg8g=~0~-1~-1; bm_sv=7665E08DA42C3C41446FC49C5D6B578A~YAAQpV06F0XNLl6RAQAA9luWfhiX0VZm9qfTEzvvG5giMN1MOMtG0mPFqmjBR2BdWxqhl4COM3QDJ6C68YQC22ke1Pf75TIdXcgd6KsUHx6BrVAdpch5eL3yiQwy50DBLYjWgiq3Wj50FWL8sT8CHW6IILwF2+iSPcies18jvGlMavCqqeuUdy7eWbWGMxQAdhWvXxbItKEQ2nsibpClnxnUKD1BgzEOJD2n2BmqEv0TD3f8F3PKs/HAr3BzD+09WjYbnQ==" \
          -H "pragma: no-cache" \
          -H "priority: u=1, i" \
          -H "referer: https://www.nseindia.com/market-data/52-week-high-equity-market" \
          -H "sec-ch-ua: \"Not)A;Brand\";v=\"99\", \"Google Chrome\";v=\"127\", \"Chromium\";v=\"127\"" \
          -H "sec-ch-ua-mobile: ?0" \
          -H "sec-ch-ua-platform: \"Windows\"" \
          -H "sec-fetch-dest: empty" \
          -H "sec-fetch-mode: cors" \
          -H "sec-fetch-site: same-origin" \
          -H "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36" \
          -o market/52-week-high.json

    - name: Commit and Push Data
      run: |
        git config --local user.name "github-actions"
        git config --local user.email "github-actions@github.com"
        git add market/52-week-high.json
        git commit -m "Update 52 Week High data"
        git push
