name: Fetch Corporate Actions Data

on:
  workflow_dispatch:  # Manual trigger via a button
  schedule:           # Auto trigger every day at 1:00 AM IST
    - cron: '30 19 * * *'    # 1:00 AM IST (7:30 PM UTC previous day)


jobs:
  fetch-corporate-actions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Fetch Corporate Actions Data
      run: |
        # Read the cookie value from the file
        COOKIES=$(cat cookies/NSE_COOKIES.txt | sed 's/cookies=//')
        
        TODAY=$(date +'%d-%m-%Y')
        SEVENTH_DAY=$(date -d '+7 days' +'%d-%m-%Y')
        mkdir -p "corporate-actions"
        curl --location "https://www.nseindia.com/api/corporates-corporateActions?index=equities&from_date=$TODAY&to_date=$SEVENTH_DAY" \
          --header 'accept: */*' \
          --header 'accept-language: en-US,en;q=0.9,hi;q=0.8,ta;q=0.7' \
          --header 'cache-control: no-cache' \
          --header "cookie: $COOKIES" \
          --header 'pragma: no-cache' \
          --header 'priority: u=1, i' \
          --header 'referer: https://www.nseindia.com/companies-listing/corporate-filings-actions' \
          --header 'sec-ch-ua: "Not)A;Brand";v="99", "Google Chrome";v="127", "Chromium";v="127"' \
          --header 'sec-ch-ua-mobile: ?0' \
          --header 'sec-ch-ua-platform: "Windows"' \
          --header 'sec-fetch-dest: empty' \
          --header 'sec-fetch-mode: cors' \
          --header 'sec-fetch-site: same-origin' \
          --header 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36' \
          -o "corporate-actions/index.json"

    - name: Commit and Push Data
      run: |
        git config --local user.name "github-actions"
        git config --local user.email "github-actions@github.com"
        git add "corporate-actions/index.json"
        git commit -m "Update Corporate Actions data"
        git push
