name: Fetch ETF Data

on:
  workflow_dispatch:

jobs:
  fetch-etf-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Fetch ETF Data
      run: |
        mkdir -p "etf"
        curl --location 'https://www.nseindia.com/api/etf' \
          --header 'accept: */*' \
          --header 'accept-language: en-US,en;q=0.9,hi;q=0.8,ta;q=0.7' \
          --header 'cache-control: no-cache' \
          --header 'cookie: _ga=GA1.1.482592878.1723464796; defaultLang=en; AKA_A2=A; _abck=A2F2C7BE639605F40900B55F79849635~0~YAAQdF06Fwi7YXCRAQAAchbafgwL6KZphM+3FvTsgj5u4XwVJ0QFS++GWso1roJrAYqVyQmAef4eM3oJqcIScSfU4KlmVJh37FfN6iCudIsk7lVxF77QhNlc7PHoohWxun5Dnkf20yBl0wHED49ZUKhbpzsklaVKuD5FaX9Z9voU1RO/CgyeyTucAvT3KI0n6QKhi0Sy+DNgYlArsnu2hyRDz2R35C9SBzjau3un0pXHbeMIzpjM+NmQX8lIHDA6X/B6vhVPq+nCiaxOApuOSDztFugs+19PFAPvWYmeMwv5M2+jzyIpRbMslr4Fm8w62JCTb2y09+vhmzJzLnxJWK4XUFUMCY5vzDBfj5K+klZegpKNlBt+YNQnO3ufF+yslyjW1GRPRDDKwZayL0tUK8hjUhrzkujwoTw=~-1~-1~-1; ak_bmsc=8599BEAA8443E79E3D2D726F3428B65E~000000000000000000000000000000~YAAQdF06F5m7YXCRAQAAXR/afhiUOhA8e7+afj89Dr2nsGIt6IClXM6ayH2/0Ke8NFCsrA2+m008bVSd73NiSnKOFQFCMPRpg1sjzepxPgHqhMovRaPP9bZJbnbGsXgKmv7OymoU9iHuFyniZ11X1FkwcR0IIRIYfEp7ukwOWYvxkZsp7Rp6FmSMsKxzDnEKQ6uOr/gnXWD6gOQ++Mk9aPW6P6z3ufKyTb5L0p8rAAQIpnH+A1/rfCixqXzlN7OU5pvG/iQtLOyCPYI0BAz1nsvdpAANBtDaptHF0omncllSPVqHkTf+EmOABgBbo+quTFcDwwTfNGitDkbnyBnUJi9rl9/cLRNh6GGzdUuVSk7lRYMcQIHcys9CgUFSyI0Y8hXXGeGWuD3iSzdAQxamIVe6jo4VA4Kx/EQg2917b0tANMlPlY1fVYHehzWIBlwhB2FxL3bwbgNSIhuoLEA=; nseQuoteSymbols=[{"symbol":"NV20BEES","identifier":null,"type":"equity"}]; nsit=OMgMZGKNu9jRLBB7KJuELS4R; nseappid=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcGkubnNlIiwiYXVkIjoiYXBpLm5zZSIsImlhdCI6MTcyNDQxMDk2MiwiZXhwIjoxNzI0NDE4MTYyfQ.TSFrm0-rFpysI-5GT0hDnNeuiKxx443N-TLkJXrlCy4; bm_sz=9F2BCB3CFE62F459FFEE58BB8C523CB0~YAAQRV06F0f/RV+RAQAAoyLnfhgHrJh0GksTSxXLs5sdD8ZdOc1myvLv7pug+IYHclL3zAqlTGGbzJc3VwRQiHt0gcv8wA+pYbhKDK8mmOZL1a1V6WADjKBzpTjOh0wL8eV18S9NXDDQ86PLhF654UcMX9GpQzCgMtj/uB0oRlWDSrIu/WJTExSySAY4V0jhA7a3yVHKAqnGQbY95d+Icrk+DnxCzl0MUsBcI12GYWfMpkVlsWcJ9S8Wes38UU6+RMVXYqt3grg2xQW9le27saGdipYy3Lq8LzUN6CTn9/uSAaWCO5EnluS+TnkxrWgovZHnYVjVnjekwVyx3GaQdNIWhQAHcck5Rp/fVf4HjVHCoPCbMykwAM13vy7wxPh4cdnwctzCUcMMaRN2ManEIDwbYX4YWLMANn77sw==~4471089~3622212; RT="z=1&dm=nseindia.com&si=5fd1e2ae-9fa0-4a5b-a0a1-143f247336d0&ss=m06l95oh&sl=0&se=8c&tt=0&bcn=%2F%2F684d0d45.akstat.io%2F"; _ga_87M7PJ3R97=GS1.1.1724410108.3.1.1724410964.24.0.0; bm_sv=0307EB51A6D1F7DCC9225537EEB17E05~YAAQRV06F14ARl+RAQAAizLnfhjdcxTfkDCrILYXOU8JXKZy5BENsnwmfnBSedIIhDFOBaXHFOdbTCv7zrDi/EjxGhrc0+yoNiQVxHLzmu+Mgdk7womE2UTXTTS/lDk6gCFTJRhJSulehD3vRb4uSBwNvyuIIEeVfaX5KA5ETYzw/w4TLd2JjWxwdHK75f13DLMFgwbKJSr3TSjZ9QpvlduNx7yiNHbG6WVFf6jfLFQS2hsem3SAupJDuSES5AMWHw9w~1; _abck=A2F2C7BE639605F40900B55F79849635~-1~YAAQXF06F8Jm/XWRAQAAtbDpfgzREiRyGAFQ4p4W/wooovmSmww77mWWbA6yr1w0obEkhH68kUBmrfP86vRdEancgKDNPy/GkvJh38m6inrz+m/X3UMavM7vFjSMniEZDh7GkqTl7CYk7WNCLT66XyuXBWYaat2V5PG18gu+x4rSf5cTHnX6Rq+OCczw5RGWmlUN7V381UQf07OCxHZEfThruXSWwLPPcH3JfYwdtprcFFPj/yJwd159JQrqFakNqAQkWzMpJsGP0sXzhILTlUcupuyZOdYqZXGTilFETcdkdMx/nsSkWUueFqjFGQrbxfgTrxl/soNjknmZm+5mYRkn6/uy724bmisxkOzDHjtt3sRqMOjq9FDSAoKeav8yydOx2hBZnlyyNPz1e0RbPDnRJ80PK7cx89U=~0~-1~-1; bm_sv=0307EB51A6D1F7DCC9225537EEB17E05~YAAQXF06F8Nm/XWRAQAAtbDpfhh2wHaGe0NMlJRgQn+G5Va7RhvSMklOVBVOB/ICjZhDPROfWRHU27I8h1Krd5iZfVw0YT9/PJ8baZrlJ9sdeAxQ7CByEldzIQKxyMxMIUjzUmEUa08/6ZlmkgJRStkXAeHhjYAd6Kub9rlgh+UzkKRP76QMX1ZdbWB5lwIPvxtvOKK25ZPaASL/xRvDfi/qlGRWjB1CAu6m9/jOfMA2Iea50vU0fDXHb/0EmVcFuVTh~1' \
          --header 'pragma: no-cache' \
          --header 'priority: u=1, i' \
          --header 'referer: https://www.nseindia.com/market-data/exchange-traded-funds-etf' \
          --header 'sec-ch-ua: "Not)A;Brand";v="99", "Google Chrome";v="127", "Chromium";v="127"' \
          --header 'sec-ch-ua-mobile: ?0' \
          --header 'sec-ch-ua-platform: "Windows"' \
          --header 'sec-fetch-dest: empty' \
          --header 'sec-fetch-mode: cors' \
          --header 'sec-fetch-site: same-origin' \
          --header 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36' \
          -o "etf/index.json"

    - name: Commit and Push Data
      run: |
        git config --local user.name "github-actions"
        git config --local user.email "github-actions@github.com"
        git add "etf/index.json"
        git commit -m "Update ETF data"
        git push
