name: Fetch NSE Circular Data

on:
  schedule:
    # Runs every day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allows manual triggering from the GitHub Actions tab

jobs:
  fetch-nse-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Fetch NSE Data
      run: |
        # Install necessary dependencies
        npm install axios

        # Create the directory for circulars if it doesn't exist
        mkdir -p circulars/nse

        # Fetch the NSE data
        node <<'EOF'
        const axios = require('axios');
        const fs = require('fs');

        // URL to get the cookies
        const cookieUrl = 'https://raw.githubusercontent.com/tradient0/cookies/main/cookies/NSE_COOKIES.txt';

        async function fetchNSEData() {
          try {
            console.log('Fetching cookies...');
            const cookieResponse = await axios.get(cookieUrl);
            const cookies = cookieResponse.data.replace('cookies=', '').trim();
            console.log('Cookies fetched: ', cookies);

            const headers = {
              'accept': '*/*',
              'accept-language': 'en-US,en;q=0.9',
              'cache-control': 'no-cache',
              'cookie': cookies,
              'pragma': 'no-cache',
              'priority': 'u=1, i',
              'referer': 'https://www.nseindia.com/resources/exchange-communication-circulars',
              'sec-ch-ua': '"Chromium";v="128", "Not;A=Brand";v="24", "Google Chrome";v="128"',
              'sec-ch-ua-mobile': '?0',
              'sec-ch-ua-platform': '"Windows"',
              'sec-fetch-dest': 'empty',
              'sec-fetch-mode': 'cors',
              'sec-fetch-site': 'same-origin',
              'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36'
            };

            const apiUrl = 'https://www.nseindia.com/api/circulars?fromDate=9-08-2024&toDate=9-09-2024';
            console.log('Fetching NSE data from API...');
            const response = await axios.get(apiUrl, { headers });
            console.log('NSE data fetched successfully.');

            const data = response.data.data;

            // Save the fetched data as JSON in circulars/nse/index.json
            const outputFilePath = 'circulars/nse/index.json';
            fs.writeFileSync(outputFilePath, JSON.stringify(data, null, 2));
            console.log(`Data saved to ${outputFilePath}`);
          } catch (error) {
            console.error('Error fetching NSE data:', error.message);
            process.exit(1);  // Exit the process with an error code
          }
        }

        fetchNSEData();
        EOF

    - name: Commit and Push Data
      run: |
        git config --local user.name "github-actions"
        git config --local user.email "github-actions@github.com"
        git add "circulars/nse/index.json"
        git commit -m "Update NSE Circulars data"
        git push
