name: Fetch NSE Circular Data

on:
  schedule:
    # Runs every day at 00:00, 08:00, and 16:00 UTC
    - cron: '0 0 * * *'   # 00:00 UTC
    - cron: '0 8 * * *'   # 08:00 UTC
    - cron: '0 16 * * *'  # 16:00 UTC
  workflow_dispatch:  # Allows manual triggering from the GitHub Actions tab

jobs:
  fetch-nse-circulars:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Fetch Cookies from URL and Set Environment Variable
      run: |
        # Fetch cookies from the URL and store them in a variable
        COOKIES=$(curl -s https://raw.githubusercontent.com/tradient0/cookies/main/cookies/NSE_COOKIES.txt | sed 's/cookies=//')
        echo "Cookies fetched: $COOKIES"
        
        # Set the COOKIES environment variable for later steps
        echo "COOKIES=$COOKIES" >> $GITHUB_ENV

    - name: Set Date Variables and Echo
      run: |
        # Set the date range in the desired format (DD-MM-YYYY)
        FROM_DATE=$(date +'%d-%m-%Y' -d "$(date +'%Y-%m-01')")
        TO_DATE=$(date +'%d-%m-%Y')

        # Echo the dates for verification
        echo "From Date: $FROM_DATE"
        echo "To Date: $TO_DATE"

        # Set the environment variables for dates
        echo "FROM_DATE=$FROM_DATE" >> $GITHUB_ENV
        echo "TO_DATE=$TO_DATE" >> $GITHUB_ENV

    - name: Fetch NSE Circulars Data from Start of Month to Today
      run: |
        # Create the directory for circulars if it doesn't exist
        mkdir -p "circulars/nse"

        # Use curl to fetch the NSE circulars data (from start of month to today)
        curl --location "https://www.nseindia.com/api/circulars?fromDate=$FROM_DATE&toDate=$TO_DATE" \
          --header 'accept: */*' \
          --header 'accept-language: en-US,en;q=0.9' \
          --header 'cache-control: no-cache' \
          --header "cookie: \"$COOKIES\"" \
          --header 'pragma: no-cache' \
          --header 'priority: u=1, i' \
          --header 'referer: https://www.nseindia.com/resources/exchange-communication-circulars' \
          --header 'sec-ch-ua: "Chromium";v="128", "Not;A=Brand";v="24", "Google Chrome";v="128"' \
          --header 'sec-ch-ua-mobile: ?0' \
          --header 'sec-ch-ua-platform: "Windows"' \
          --header 'sec-fetch-dest: empty' \
          --header 'sec-fetch-mode: cors' \
          --header 'sec-fetch-site: same-origin' \
          --header 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36' \
          -o "circulars/nse/index.json"

    - name: Fetch NSE Circulars Data for Today Only
      run: |
        # Set the date range for today in the desired format (DD-MM-YYYY)
        TODAY=$(date +'%d-%m-%Y')

        # Echo today's date for verification
        echo "Today's Date: $TODAY"

        # Create the directory for today's circulars if it doesn't exist
        mkdir -p "circulars/nse/today"

        # Use curl to fetch the NSE circulars data (today's date)
        curl --location "https://www.nseindia.com/api/circulars?fromDate=$TODAY&toDate=$TODAY" \
          --header 'accept: */*' \
          --header 'accept-language: en-US,en;q=0.9' \
          --header 'cache-control: no-cache' \
          --header "cookie: \"$COOKIES\"" \
          --header 'pragma: no-cache' \
          --header 'priority: u=1, i' \
          --header 'referer: https://www.nseindia.com/resources/exchange-communication-circulars' \
          --header 'sec-ch-ua: "Chromium";v="128", "Not;A=Brand";v="24", "Google Chrome";v="128"' \
          --header 'sec-ch-ua-mobile: ?0' \
          --header 'sec-ch-ua-platform: "Windows"' \
          --header 'sec-fetch-dest: empty' \
          --header 'sec-fetch-mode: cors' \
          --header 'sec-fetch-site: same-origin' \
          --header 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36' \
          -o "circulars/nse/today/index.json"

    - name: Commit and Push Data
      run: |
        git config --local user.name "github-actions"
        git config --local user.email "github-actions@github.com"
        git add "circulars/nse/index.json"
        git add "circulars/nse/today/index.json"
        git commit -m "Update NSE Circulars data"
        git push
