name: Fetch CDSL Circular Data

on:
  schedule:
    - cron: '0 0 * * *'   # 00:00 UTC
    - cron: '0 6 * * *'   # 06:00 UTC
    - cron: '0 12 * * *'  # 12:00 UTC
    - cron: '0 18 * * *'  # 18:00 UTC
    - cron: '0 23 * * *'  # 23:00 UTC
  workflow_dispatch:  # Allows manual triggering from the GitHub Actions tab

jobs:
  fetch-cdsl-circulars:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Fetch CDSL Circulars Data as HTML
      run: |
        # Create directory for CDSL circulars if it doesn't exist
        mkdir -p "circulars/cdsl"

        # Fetch the HTML page from CDSL's website and save it
        curl --location "https://www.cdslindia.com/Publications/Communique.aspx#" -o "circulars/cdsl/cdsl_page.html"

    - name: Install Python and pipx
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip install --user pipx
        export PATH="$HOME/.local/bin:$PATH"
        pipx ensurepath

    - name: Install BeautifulSoup4 using pipx
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        pipx install beautifulsoup4

    - name: Run the Python Script to Convert HTML to JSON
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        pipx run --spec beautifulsoup4 python3 script/cdsl.py

    - name: Commit and Push Data
      run: |
        git config --local user.name "github-actions"
        git config --local user.email "github-actions@github.com"
        git add "circulars/cdsl/index.json"
        git commit -m "Update CDSL Circulars data"
        git push
